[program:cape]
command=/opt/CAPEv2/venv/bin/python3 cuckoo.py
directory=/opt/CAPEv2
user=cape
autostart=true
autorestart=true
stderr_logfile=/opt/CAPEv2/log/cape.err.log
stdout_logfile=/opt/CAPEv2/log/cape.out.log
startsecs=10

[program:cape-web]
command=/opt/CAPEv2/venv/bin/python3 manage.py runserver 0.0.0.0:8000
directory=/opt/CAPEv2/web
user=cape
autostart=true
autorestart=true
stderr_logfile=/opt/CAPEv2/log/web.err.log
stdout_logfile=/opt/CAPEv2/log/web.out.log
startsecs=5

[program:cape-processor]
command=/opt/CAPEv2/venv/bin/python3 process.py auto
directory=/opt/CAPEv2/utils
user=cape
autostart=true
autorestart=true
stderr_logfile=/opt/CAPEv2/log/processor.err.log
stdout_logfile=/opt/CAPEv2/log/processor.out.log
startsecs=10

[program:cape-rooter]
command=/opt/CAPEv2/venv/bin/python3 rooter.py
directory=/opt/CAPEv2/utils
user=root
autostart=true
autorestart=true
stderr_logfile=/opt/CAPEv2/log/rooter.err.log
stdout_logfile=/opt/CAPEv2/log/rooter.out.log
startsecs=5
